Repository btford/write-good, pull requests merged in 2019-01, with the labels that each got.

#107 Update README.md
  README.md
Labels: enhancement, waiting on contributor

#109 Update code to node 6, add linter, update deps
  .eslintrc
  .travis.yml
  Dockerfile
  LICENSE
  bin/write-good.js
  lib/annotate.js
  lib/lexical-illusions.js
  lib/starts-with-so.js
  lib/there-is.js
  package-lock.json
  package.json
  test/.eslintrc
  test/basic.spec.js
  test/cli.spec.js
  test/customChecks.spec.js
  write-good.js
Labels: enhancement, needs re-review

#111 bump deps for some plugins
  package-lock.json
  package.json
Labels: needs review
